// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvZXDYP5Ai7zusIl1862dturpoP916JQ',
    appId: '1:224483615941:web:d12b82789f146db09bbcac',
    messagingSenderId: '224483615941',
    projectId: 'sanvadaplus',
    authDomain: 'sanvadaplus.firebaseapp.com',
    storageBucket: 'sanvadaplus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2eMQfv0cS84nmoo0174mXL08rTsMahOE',
    appId: '1:224483615941:android:feec48d908a835119bbcac',
    messagingSenderId: '224483615941',
    projectId: 'sanvadaplus',
    storageBucket: 'sanvadaplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5uhl6czPC_DmhIaGxxYN6DIMd15BmnBw',
    appId: '1:224483615941:ios:8de67fe0fa5dfe919bbcac',
    messagingSenderId: '224483615941',
    projectId: 'sanvadaplus',
    storageBucket: 'sanvadaplus.firebasestorage.app',
    iosBundleId: 'com.sanvadaplus.sanvadaPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5uhl6czPC_DmhIaGxxYN6DIMd15BmnBw',
    appId: '1:224483615941:ios:8de67fe0fa5dfe919bbcac',
    messagingSenderId: '224483615941',
    projectId: 'sanvadaplus',
    storageBucket: 'sanvadaplus.firebasestorage.app',
    iosBundleId: 'com.sanvadaplus.sanvadaPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUvZXDYP5Ai7zusIl1862dturpoP916JQ',
    appId: '1:224483615941:web:7861d2f38a53b0bc9bbcac',
    messagingSenderId: '224483615941',
    projectId: 'sanvadaplus',
    authDomain: 'sanvadaplus.firebaseapp.com',
    storageBucket: 'sanvadaplus.firebasestorage.app',
  );
}
